name: personsApp

services:
  db:
    image: mysql:8.3.0
    volumes:
      - db_data:/var/lib/mysql
      - ./dumpGestbook.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestbook
  api:
    depends_on:
      - db
    image: api_image
    ports:
      - "8080:8080"
    environment:
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gestbook
    restart: always
  webapp:
    depends_on:
      - api
    image: webapp_image
    ports:
      - "8081:8081"
    environment:
      - FR.JULIUSELGRINGO.DEMOSPRINGWEBAPP.APIURL=http://api:8080
    restart: always
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "9090:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
volumes:
  db_data: